image: "cypress/base:12.16.1"

stages:
  - build
  - test

# to cache Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache: &node
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn
    - cache/Cypress

install:
  stage: build
  script:
    - yarn install --pure-lockfile --cache-folder .yarn

test:
  stage: test
  cache: *node
  services:
    - mongo:latest
  variables:
    DB_URI: "mongodb://mongo:27017"
  script:
    - yarn test
    - yarn e2e
