image: "cypress/base:12.16.1"

stages:
  - test

cache: &node
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn
    - .npm
    - .cache/Cypress

test:
  stage: test
  cache: *node
  services:
    - name: khezen/mongo:4.2
      alias: mongo
  variables:
    AUTH: n
    DB_NAME: nx-mean-starter-test

  script:
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn test
    - yarn e2e
