image: "cypress/base:12.16.1"

stages:
  - test

cache: &node
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn
    - .npm
    - .cache/Cypress

test:
  cache: *node
  services:
    - mongo:latest
  script:
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn test
    - yarn e2e
